electionscience/vote.electionscience.org

.gitignore
README.md
requirements.txt

Added (alternate) instructions for using pip and virtualenv to install dependencies and also formatted the readme file.

Introduce the pip+virtualenv method for deps

---

approval_frame/backends.py
approval_frame/forms.py
approval_frame/settings.py
approval_frame/templates/registration/login.html
approval_frame/tests.py
approval_frame/urls.py

Added a custom backend for user authentication with either email or password - https://github.com/electology/approval_frame/issues/32 . Before logging in with an email, one needs to make sure that there are no duplicate email records in the database.

Allow user login with either username or email ID.

---

approval_frame/backends.py
approval_polls/migrations/0003_ballot_user.py
approval_polls/migrations/0004_poll_vtype.py
approval_polls/models.py
approval_polls/static/approval_polls/embed_instructions.js
approval_polls/templates/approval_polls/create.html
approval_polls/templates/approval_polls/detail.html
approval_polls/templates/approval_polls/embed_instructions.html
approval_polls/templates/approval_polls/results.html
approval_polls/templates/base.html
approval_polls/views.py

https://github.com/electology/approval_frame/issues/16
Added a 'Poll Settings' panel in the 'create poll' page - through which the poll administrator can control who can vote in the poll.
It now allows two types of polls:
1) Anyone can vote, any number of times (previous behavior)
2) Only registered voters can vote, once - requires login. 
This does not include the ability to update ones existing ballot. We could perhaps handle that in another ticket.

Issue 16 track voters

---

approval_polls/templates/approval_polls/create.html
approval_polls/tests.py

https://github.com/electology/approval_frame/issues/16

Fixed tests. Minor formatting according to PEP.

---

approval_polls/static/approval_polls/embed_instructions.js
approval_polls/static/approval_polls/style.css
approval_polls/templates/approval_polls/embed_instructions.html

Created a 'Copy to Clipboard' button to copy HTML Code snippet in
'embed_instructions'  page to Clipboard.
Show a message depending on success or failure.

Issue 80 - Allow user to copy html code

---

README.md
approval_frame/backends.py
approval_frame/forms.py
approval_frame/tests.py
approval_frame/urls.py
approval_frame/views.py
approval_frame/wsgi.py
approval_polls/admin.py
approval_polls/migrations/0001_initial.py
approval_polls/migrations/0002_poll_user.py
approval_polls/migrations/0003_ballot_user.py
approval_polls/migrations/0004_poll_vtype.py
approval_polls/models.py
approval_polls/static/approval_polls/create.js
approval_polls/static/approval_polls/embed_instructions.js
approval_polls/templatetags/filters.py
approval_polls/tests.py
approval_polls/urls.py
approval_polls/views.py
setup.cfg

* Added notes for coding style guidelines, local settings and testing in README.md.
* Added setup.cfg with flake8 config.
* Cleaned up code to conform to flake8 and JSHint.
https://github.com/electology/approval_frame/issues/83

Issue 83 - Add Style guide, settings, testing edits.

---

.gitignore
README.md
approval_frame/settings.py
approval_frame/wsgi.py
approval_polls/templates/404.html
requirements.txt

* Added support and docs for handling static files in production when DEBUG=FALSE
* Makes use of dj-static.
* Added a 404.html page (page not found).
https://github.com/electology/approval_frame/issues/62

Issue 62: Serve static files in production when DEBUG=FALSE

---

LICENSE
README.md

* Adding [GNU GPLv3](http://www.gnu.org/licenses/gpl-3.0.en.html) LICENSE file to the project. 
* Minor doc change.

Issue 87 add license file

---

approval_polls/static/approval_polls/create.js
approval_polls/views.py

1. Fixed bugs related to functionality of Jquery DateTime Picker.
2. Fixed bug related to voting/updating vote after the poll's close
datetime.

Issue75: Fixed bugs

---

approval_polls/migrations/0008_poll_show_write_in.py
approval_polls/migrations/0009_poll_show_lead_color.py
approval_polls/models.py
approval_polls/static/approval_polls/detail.js
approval_polls/static/approval_polls/my_polls.js
approval_polls/static/approval_polls/style.css
approval_polls/templates/approval_polls/create.html
approval_polls/templates/approval_polls/detail.html
approval_polls/templates/approval_polls/my_polls.html
approval_polls/templates/approval_polls/results.html
approval_polls/tests.py
approval_polls/views.py

1. A user can delete a poll by clicking 'remove' button in 'My Polls'
page.
2. If a poll administrator has allowed a write-in option for a poll, a
participant can add an additional option by typing it in and select that
option if they choose.
3. Allow a poll to be configured to display the option with the leading
number of votes in a different color.

Resolved Issue 65, 49 and 78

---

approval_polls/models.py
approval_polls/templates/approval_polls/invitation_email_body.html
approval_polls/views.py

Fixed the case when an existing user is sent an invitation to vote by email.
https://github.com/electology/approval_frame/issues/47

Part of Issue 47 - Limit voters to users with emails set by the poll admin.

---

approval_polls/static/approval_polls/create.js
approval_polls/static/approval_polls/detail.js

Modified Regex to validate more URLs
Use Regex from Jquery Validation project

Issue 77 - Allow more URLs

---

.gitignore
README.md
approval_frame/forms.py
approval_frame/mailchimp_api.py
approval_frame/templates/registration/registration_form.html
approval_frame/urls.py
approval_frame/views.py
approval_polls/static/approval_polls/registration_form.js
requirements.txt

- User can sign up for a newsletter on registration
- A confirmation mail is sent to user to confirm newsletter subscription

Issue 33 - Opt-in newsletter

---

approval_polls/static/approval_polls/create.js
approval_polls/templates/approval_polls/create.html

add "X" button and JS to remove choice fields

---

approval_polls/static/approval_polls/detail.js
approval_polls/static/vendor/js-socials/jssocials-theme-flat.css
approval_polls/static/vendor/js-socials/jssocials.css
approval_polls/static/vendor/js-socials/jssocials.js
approval_polls/templates/approval_polls/detail.html
approval_polls/templates/base.html

Use JsSocials plugin in order to add social media sharing icons to polls.
Example:

Fix #121: Add JsSocials plugin for social media sharing

---

approval_frame/forms.py
approval_frame/mailchimp_api.py
approval_frame/templates/registration/subscription_change_done.html
approval_frame/templates/registration/subscription_preferences.html
approval_frame/urls.py
approval_frame/views.py
approval_polls/migrations/0012_subscription.py
approval_polls/models.py
approval_polls/templates/approval_polls/my_info.html

@rupalkhilari Please review this PR for adding subscription for logged in users. It works successfully if you add the zipcode and check the box properly. However, when you check the box and don't enter the zipcode, it gives an error 
I have re-used some of the validations and UI elements from the registration form . Please feel free to give feedback.
Thanks!

Adding user subscriptions for logged in user

---

approval_polls/static/approval_polls/edit.js
approval_polls/templates/approval_polls/edit.html
approval_polls/templates/approval_polls/my_polls.html
approval_polls/urls.py
approval_polls/views.py

This addresses issue #110. It also adds an edit page which should help for addressing #108, #109, #111.

Edit page for close time and countdown

---

README.md
approval_frame/approval_frame_cron
approval_frame/mailchimp_api.py
approval_frame/scripts/update_user_subscriptions.py
approval_frame/settings.py
requirements.txt

https://github.com/electology/approval_frame/issues/124
Dependencies: https://github.com/electology/approval_frame/pull/122 to be merged

Update users subscriptions

---

approval_polls/static/approval_polls/create.js
approval_polls/templates/approval_polls/create.html
approval_polls/views.py

* Changes `create.js` to never decrement numChoices. This prevents duplicate choices from happening.
* Changes `CreateView.post` in `views.py` to handle choices not being contiguous. (ie 'choice1', 'choice3')
#132

Changed how choices are handled to fix #132.

---

approval_polls/templates/approval_polls/edit.html
approval_polls/views.py

Addresses #111. It's fairly minor. It's just adding 2 more booleans to the form and post handling.

Added write-in and leading color options to edit page.

---

approval_frame/settings.py
approval_polls/migrations/0013_poll_is_suspended.py
approval_polls/models.py
approval_polls/static/approval_polls/my_polls.js
approval_polls/templates/approval_polls/detail.html
approval_polls/templates/approval_polls/my_polls.html
approval_polls/templatetags/filters.py
approval_polls/tests.py
approval_polls/urls.py
approval_polls/views.py
requirements.txt

https://github.com/electology/approval_frame/issues/67
* new column to poll is_suspended
* Adds djangoajax. (In this case, used to suspend and unsuspend polls)
* Disables voting for suspended polls

Poll suspension

---

approval_polls/static/approval_polls/detail.js

Can someone please check if this fix is sufficient ? I couldn't see the error after this check was added.
Any other comments or suggestions are also welcome.

Bug fix : TypeError in detail.js when poll created with no countdown #125

---

approval_polls/models.py
approval_polls/templates/approval_polls/create.html
approval_polls/templates/approval_polls/edit.html
approval_polls/templates/approval_polls/tag_cloud.html
approval_polls/templates/base.html
approval_polls/tests.py
approval_polls/urls.py
approval_polls/views.py

https://github.com/electology/approval_frame/issues/149

Adding link to tag_cloud below logo

---

approval_polls/static/approval_polls/create.js
approval_polls/templates/approval_polls/edit.html
approval_polls/tests.py

https://github.com/electology/approval_frame/issues/135

Editing a poll's choice links

---

approval_polls/models.py
approval_polls/templates/approval_polls/results.html

Resolves: https://github.com/electology/approval_frame/issues/162

Sort result choices based on number of votes.

---

approval_polls/templates/approval_polls/create.html

Change default option to allow anyone to vote without requiring login.

---

approval_frame/urls.py

Resolves https://github.com/electionscience/approval_frame/issues/166

Redirect to home page to approval poll page.

---

approval_polls/admin.py
approval_polls/migrations/0015_email_opt_in.py
approval_polls/migrations/0016_update_email_opt_in.py
approval_polls/migrations/0017_ballot_remove_unique_email.py
approval_polls/models.py
approval_polls/static/approval_polls/style.css
approval_polls/templates/approval_polls/create.html
approval_polls/templates/approval_polls/detail.html
approval_polls/templates/approval_polls/edit.html
approval_polls/templates/approval_polls/embed_instructions.html
approval_polls/tests.py
approval_polls/views.py

Issue 170 add opt in for email

---

approval_frame/forms.py
approval_frame/middleware/timezone_middleware.py
approval_frame/scripts/update_user_subscriptions.py
approval_frame/views.py
approval_polls/models.py
approval_polls/templatetags/filters.py
approval_polls/tests.py
approval_polls/views.py

Reverts electionscience/approval_frame#187

Revert "Sourcery refactored main branch"
